apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc 
